[project]
name = "server"
version = "0.1.0"
description = "A server application for African Insights Navigator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.33",
    "langgraph>=0.6.7",
    "pydantic-settings>=2.10.1",
    "streamlit>=1.49.1",
    "tavily-python>=0.7.11",
    "uvicorn>=0.35.0",
    "dotenv>=0.9.9",
    "langchain-tavily>=0.2.11",
    "langchain-huggingface>=0.3.1",
    "langchain-google-genai>=2.1.12",
    "llama-index>=0.14.2",
    "langchain-chroma>=0.2.6",
    "langchain-text-splitters>=0.3.11",
    "langchain-community>=0.3.29",
    "pypdf>=6.1.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.7",
    "langchain-ollama>=0.3.7",
    "langchain-tavily>=0.2.11",
    "langgraph-cli[inmem]>=0.4.2",
    "llama-index-embeddings-huggingface>=0.6.1",
    "llama-index-embeddings-ollama>=0.8.3",
    "llama-index-llms-ollama>=0.7.3",
    "pytest>=8.4.2",
]
